jobs:
- job: cargo_test_all
  displayName: cargo test
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      # TODO: Enable when possible
      #
      # stable:
      #   rust_version: stable
      # beta:
      #   rust_version: beta
      nightly:
        rust_version: nightly
  steps:

  - template: azure-install-rust.yml
    parameters:
      rust_version: $(rust_version)

  - script: cargo test
    displayName: cargo test

  # Check with serde based checkpoint feature
  - script: cargo check --features checkpoint
    displayName: cargo check --features checkpoint

  # Test with futures feature
  - script: cargo test --features futures
    displayName: cargo test --features futures

  # Test with lock_api feature
  - script: cargo test --features lock_api
    displayName: cargo test --features lock_api
