# automatically publish GitHub releases for release tags
name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    # only publish from the origin repository
    if: github.repository_owner == 'tokio-rs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: "Loom $version"
          branch: master
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}